# Definitions
build_tool = runtime-container.DONE
name = quay.io/ucsc_cgl/rnaseq-cgl-pipeline
git_commit ?= $(shell git log --pretty=oneline -n 1 | cut -f1 -d " ")

#find the line with grep, trim whitespace, extract the text after the equals sign trim single quotes
toil_rnaseq_version := $(shell grep '^version =' ../../version.py | tr -d [:space:] | cut -d= -f2- | tr -d "'")

short_tag = ${toil_rnaseq_version}-DOCKERVER
long_tag = ${short_tag}-${git_commit}

sdist:
	cp ../../dist/toil-rnaseq*.tar.gz ./toil-rnaseq.tar.gz

build: sdist Dockerfile
	docker build -t ${name}:${long_tag} .
	-docker rmi -f ${name}:${short_tag}
	docker tag ${name}:${long_tag} ${name}:${short_tag}
	touch ${build_tool}

push: build
	# Requires ~/.dockercfg
	docker push ${name}:${short_tag}
	
test: build
	python test.py ${long_tag}

clean:
	docker rmi -f ${name}:${short_tag}
	rm ${build_tool}
